package iris.vk.api

/**
 * @created 28.10.2020
 * @author [Ivan Ivanov](https://vk.com/irisism)
 */
const val VK_API_VERSION = "5.124"

const val VK_BOT_ERROR_UNKNOWN = 1
const val VK_BOT_ERROR_APP_IS_OFF = 2
const val VK_BOT_ERROR_UNKNOWN_METHOD = 3
const val VK_BOT_ERROR_WRONG_TOKEN = 4
const val VK_BOT_ERROR_AUTH_FAILED = 5
const val VK_BOT_ERROR_TOO_MANY_REQUESTS = 6
const val VK_BOT_ERROR_NO_RIGHTS_FOR_ACTION = 7
const val VK_BOT_ERROR_WRONG_REQUEST = 8
const val VK_BOT_ERROR_ONE_TYPE_ACTIONS = 9
const val VK_BOT_ERROR_INTERNAL = 10
const val VK_BOT_ERROR_TEST_MODE_APP_MUST_BE_OFF = 11
const val VK_BOT_ERROR_CAPTCHA = 14
const val VK_BOT_ERROR_ACCESS_DENIED = 15
const val VK_BOT_ERROR_HTTPS_REQUIRED = 16
const val VK_BOT_ERROR_VALIDATION_REQUIRED = 17
const val VK_BOT_ERROR_PAGE_DELETED = 18
const val VK_BOT_ERROR_ACTION_DENIED_FOR_STANDALONE = 20
const val VK_BOT_ERROR_ACTION_ALLOWED_ONLY_FOR_STANDALONE = 21
const val VK_BOT_ERROR_METHOD_IS_OFF = 23
const val VK_BOT_ERROR_USER_CONFIRMATION_REQUIRED = 24
const val VK_BOT_ERROR_GROUP_TOKEN_IS_INVALID = 27
const val VK_BOT_ERROR_APP_TOKEN_IS_INVALID = 28
const val VK_BOT_ERROR_DATA_REQUEST_LIMIT = 29
const val VK_BOT_ERROR_PROFILE_IS_PRIVATE = 30
const val VK_BOT_ERROR_ONE_OF_PARAMETERS_IS_WRONG = 100
const val VK_BOT_ERROR_WRONG_APP_API = 101
const val VK_BOT_ERROR_WRONG_USER_ID = 113
const val VK_BOT_ERROR_WRONG_TIMESTAMP = 150
const val VK_BOT_ERROR_USER_NOT_FOUND = 177
const val VK_BOT_ERROR_ALBUM_ACCESS_DENIED = 200
const val VK_BOT_ERROR_AUDIO_ACCESS_DENIED = 201
const val VK_BOT_ERROR_GROUP_ACCESS_DENIED = 203
const val VK_BOT_ERROR_ALBUM_IS_FULL = 300
const val VK_BOT_ERROR_ACTION_IS_DENIED = 500
const val VK_BOT_ERROR_NO_RIGHTS_FOR_ADV_CABINET = 600
const val VK_BOT_ERROR_IN_ADV_CABINET = 603

const val VK_BOT_ERROR_CANT_SEND_TO_USER_IN_BLACKLIST = 900
const val VK_BOT_ERROR_CANT_SEND_WITHOUT_PERMISSION = 901
const val VK_BOT_ERROR_CANT_SEND_TO_USER_PRIVACY_SETTINGS = 902
const val VK_BOT_ERROR_KEYBOARD_FORMAT_IS_INVALID = 911
const val VK_BOT_ERROR_THIS_IS_CHATBOT_FEATURE = 912
const val VK_BOT_ERROR_TOO_MANY_FORWARDED_MESSAGES = 913
const val VK_BOT_ERROR_MESSAGE_IS_TOO_LONG = 914
const val VK_BOT_ERROR_NO_ACCESS_TO_THIS_CHAT = 917
const val VK_BOT_ERROR_CANT_FORWARD_SELECTED_MESSAGES = 921
const val VK_BOT_ERROR_CANT_DELETE_FOR_ALL_USERS = 924
const val VK_BOT_ERROR_USER_NOT_FOUND_IN_CHAT = 935
const val VK_BOT_ERROR_CONTACT_NOT_FOUND = 936